// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


function EvenFibonacci(max) {


    let sum = 0;
    let a = 1;
    let b = 0;
    let temp;


    while (a < max) {

        temp = a;
        a = a + b;
        b = temp;

        if (a % 2 === 0) {
            sum += a;
        }
    }

    return sum;
}

console.log(EvenFibonacci(4000000))
